### ISSUE TITLE
Question: guideline no.16 

### ISSUE THREAD

**Issue by mgritcan** [justinamiller/DotNet-Coding-Guidelines#7]
Hi, I've seen the Coding Guideline published on [C# digest](https://csharpdigest.net/digests/351) this week. 
Thanks for summarizing all of these in a place open to community :+1:.

Guideline no.16 looks amazing!

**With the release of C# 9, We can now let the constructor do the initialization automatically:**
```
public class PersonManager    
{  
    public PersonManager(ILogger<PersonManager> _logger, 
		        SomeConfiguration _config)  
    {   
    }  
} 
```
Could you share the docs (source) for that piece of documentation please ? I'd like to study a bit more the possibilities around this optimization because I've tried it with my actual VS 2019, v16.8.5 but it doesn't work yet.

**Comment by dealdiane** [comment]
No docs because `Primary Constructors` never made it to C# 9. Was (re)planned for C# 10 but even that had been removed recently.

See https://github.com/dotnet/csharplang/issues/2691

**Comment by mgritcan** [comment]
Many thanks @dealdiane for source!
